apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hlads-web-cert
  namespace: hlads-web-ns
spec:
  dnsNames:
    - hlads.net
  secretName: hlads-web-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer