apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hlads-webcert
  namespace: default
spec:
  dnsNames:
    - hlads.net
  secretName: hlads-webtls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer