apiVersion: apps/v1
kind: Deployment
metadata:
  name: hlads-web
  namespace: hlads-web-ns
  labels:
    app: hlads-web
spec:
  replicas: 3
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  selector:
    matchLabels:
      app: hlads-web
  template:
    metadata:
      labels:
        app: hlads-web
    spec:
      containers:
      - name: hlads-web
        image: hlads/website
        imagePullPolicy: Always
        ports:
        - containerPort: 80