apiVersion: apps/v1
kind: Deployment
metadata:
  name: hlads-web
  namespace: hlads-web-ns
  labels:
    app: hlads-web
spec:
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: hlads-web
  template:
    metadata:
      labels:
        app: hlads-web
    spec:
      containers:
      - name: hlads-web
        image: hlads/website
        imagePullPolicy: Always
        resources:
          limits:
            memory: 500Mi
            cpu: "1"
          requests:
            memory: 10Mi
            cpu: 1m
        ports:
        - containerPort: 80