apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hlads-web-hpa
  namespace: hlads-web-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hlads-web
  minReplicas: 1
  maxReplicas: 16
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory 
      target:
        type: Utilization 
        averageUtilization: 75